//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteExtensions.Administration.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PackageManagerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public PackageManagerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiteExtensions.Administration.Resources.PackageManagerResources", typeof(PackageManagerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Package Source.
        /// </summary>
        public static string AddPackageSourceLabel {
            get {
                return ResourceManager.GetString("AddPackageSourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to uninstall &lt;strong&gt;{0}&lt;/strong&gt;?.
        /// </summary>
        public static string AreYouSureUninstall {
            get {
                return ResourceManager.GetString("AreYouSureUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string AuthorsLabel {
            get {
                return ResourceManager.GetString("AuthorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request.
        /// </summary>
        public static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearLabel {
            get {
                return ResourceManager.GetString("ClearLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string DefaultPackageSourceName {
            get {
                return ResourceManager.GetString("DefaultPackageSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteLabel {
            get {
                return ResourceManager.GetString("DeleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking &quot;Install&quot; you agree to the license terms for the package(s) above. If you do not agree to the license terms, click &quot;Cancel.&quot; Each package is licensed to you by its owner. Microsoft is not responsible for, nor does it grant any licenses to, third-party packages..
        /// </summary>
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string InstalledLabel {
            get {
                return ResourceManager.GetString("InstalledLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string InstallPackage {
            get {
                return ResourceManager.GetString("InstallPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing package {0}..
        /// </summary>
        public static string InstallPackageDesc {
            get {
                return ResourceManager.GetString("InstallPackageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package &lt;strong&gt;{0}&lt;/strong&gt; was successfully installed..
        /// </summary>
        public static string InstallSuccess {
            get {
                return ResourceManager.GetString("InstallSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JavaScript is required to correctly view this page..
        /// </summary>
        public static string JavascriptRequired {
            get {
                return ResourceManager.GetString("JavascriptRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this page to manage your package sources..
        /// </summary>
        public static string ManageSourcesDesc {
            get {
                return ResourceManager.GetString("ManageSourcesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Package Sources.
        /// </summary>
        public static string ManageSourcesTitle {
            get {
                return ResourceManager.GetString("ManageSourcesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collection of tools to automate the process of installing, upgrading, configuring, and removing packages from an ASP.NET application..
        /// </summary>
        public static string ModuleDesc {
            get {
                return ResourceManager.GetString("ModuleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Manager.
        /// </summary>
        public static string ModuleTitle {
            get {
                return ResourceManager.GetString("ModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NextText {
            get {
                return ResourceManager.GetString("NextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No packages found..
        /// </summary>
        public static string NoPackagesFound {
            get {
                return ResourceManager.GetString("NoPackagesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No packages installed. &lt;p&gt;&lt;a href=&quot;{0}&quot;&gt;Install packages from an online feed&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        public static string NoPackagesInstalled {
            get {
                return ResourceManager.GetString("NoPackagesInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default (All).
        /// </summary>
        public static string NuGetFeed {
            get {
                return ResourceManager.GetString("NuGetFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string OnlineLabel {
            get {
                return ResourceManager.GetString("OnlineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error installing package &quot;{0}&quot;:.
        /// </summary>
        public static string PackageInstallationError {
            get {
                return ResourceManager.GetString("PackageInstallationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read package source file. Ensure that the file &quot;{0}&quot; is writeable and the contents of the file have not been modified externally..
        /// </summary>
        public static string PackageSourceFileInstructions {
            get {
                return ResourceManager.GetString("PackageSourceFileInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string PackageSourceLabel {
            get {
                return ResourceManager.GetString("PackageSourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred uninstalling package &quot;{0}&quot;:.
        /// </summary>
        public static string PackageUninstallationError {
            get {
                return ResourceManager.GetString("PackageUninstallationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred updating package &quot;{0}&quot;:.
        /// </summary>
        public static string PackageUpdateError {
            get {
                return ResourceManager.GetString("PackageUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string PageLabel {
            get {
                return ResourceManager.GetString("PageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string PreviousText {
            get {
                return ResourceManager.GetString("PreviousText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        public static string PrivacyStatement {
            get {
                return ResourceManager.GetString("PrivacyStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Dependencies?.
        /// </summary>
        public static string RemoveDependencies {
            get {
                return ResourceManager.GetString("RemoveDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Default .
        /// </summary>
        public static string RestoreDefaultSources {
            get {
                return ResourceManager.GetString("RestoreDefaultSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages.
        /// </summary>
        public static string SectionTitle {
            get {
                return ResourceManager.GetString("SectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string ShowLabel {
            get {
                return ResourceManager.GetString("ShowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SourceNameLabel {
            get {
                return ResourceManager.GetString("SourceNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string SourceUrlLabel {
            get {
                return ResourceManager.GetString("SourceUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string UninstallPackage {
            get {
                return ResourceManager.GetString("UninstallPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling package {0}..
        /// </summary>
        public static string UninstallPackageDesc {
            get {
                return ResourceManager.GetString("UninstallPackageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package &lt;strong&gt;{0}&lt;/strong&gt; was successfully uninstalled..
        /// </summary>
        public static string UninstallSuccess {
            get {
                return ResourceManager.GetString("UninstallSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown framework assembly: &quot;{0}&quot;.
        /// </summary>
        public static string UnknownFrameworkReference {
            get {
                return ResourceManager.GetString("UnknownFrameworkReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdatePackage {
            get {
                return ResourceManager.GetString("UpdatePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating package {0} to version {1}..
        /// </summary>
        public static string UpdatePackageDesc {
            get {
                return ResourceManager.GetString("UpdatePackageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string UpdatesLabel {
            get {
                return ResourceManager.GetString("UpdatesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package &lt;strong&gt;{0}&lt;/strong&gt; was successfully updated..
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid source url..
        /// </summary>
        public static string Validation_InvalidPackageSourceUrl {
            get {
                return ResourceManager.GetString("Validation_InvalidPackageSourceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified package source already exists..
        /// </summary>
        public static string Validation_PackageSourceAlreadyExists {
            get {
                return ResourceManager.GetString("Validation_PackageSourceAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View License Terms.
        /// </summary>
        public static string ViewLicenseTerms {
            get {
                return ResourceManager.GetString("ViewLicenseTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        public static string WordSeparator {
            get {
                return ResourceManager.GetString("WordSeparator", resourceCulture);
            }
        }
    }
}
